spring.datasource.url=jdbc:postgresql://dpg-d76gg5fkijhs73bh7dq0-a.singapore-postgres.render.com:5432/db_server_4
spring.datasource.username=admin
spring.datasource.password=WkkvQKPwvAhglnwUPyEhp4AQFsyMEX8H
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

server.id=4